### ISSUE TITLE
Throwing syntax error while executing the BeefOverWan.py

### ISSUE THREAD

**Issue by Shuvamoy** [stormshadow07/BeeF-Over-Wan#48]
File "/home/user/Downloads/tools/BeeF-Over-Wan/BeeFOverWan.py", line 90
    print '"{old_string}" not found in {filename}.'.format(**locals())
          ^
SyntaxError: invalid syntax

**Comment by drpain365** [comment]
Just use `python2.7 BeeFOverWan.py`

**Comment by CyberLeafy** [comment]
after use python2.7 
Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor
