### ISSUE TITLE
showing error

### ISSUE THREAD

**Issue by gonewrong2910** [stormshadow07/BeeF-Over-Wan#50]
Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by Warhammar** [comment]
I have the same failure.

**Comment by Warhammar** [comment]
─$ sudo chmod +x BeeFOverWan.py && python BeeFOverWan.py                   1 ⨯
Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by KityKat6813** [comment]
> Traceback (most recent call last):
> File "BeeFOverWan.py", line 8, in
> from termcolor import colored
> ImportError: No module named termcolor

1. nano BeeFOverWan.py
2. Locate line 8
3. comment out (form termcolor import colored)
4. #form termcolor import colored
5. Ctrl+o
6. Ctrl+x

**Comment by Warhammar** [comment]
Now the Password beef wont work..


la 17. heinäk. 2021 klo 14.36 Kitkat6813 ***@***.***)
kirjoitti:

**Comment by messaouddhia** [comment]
1.nano BeeFOverWan.py
2.Delete the line 8 completely "from termcolor import colored"
3.chmod +x BeeFOverWan.py
4.python2.7 BeeFOverWan.py

**Comment by Alexjr9777** [comment]
> Traceback (most recent call last): File "BeeFOverWan.py", line 8, in from termcolor import colored ImportError: No module named termcolor

*for linux*
download termcolor tar from python org extract it open terminal in that dir """python setup.py install""" then try the tools

it will work

**Comment by asmahdi08** [comment]
Step 1: install gedit by doing "sudo apt install gedit"

Step 2: go to your BeeF-Over-Wan directory

Step 3: do "gedit BeeFOverWan.py"

Step 4: remove the line 8 and paste " #from termcolor import colored " in line 8

Now do "python BeeFOverWan.py" and it should work perfectly

**Comment by soullessrat5** [comment]
> Step 1: install gedit by doing "sudo apt install gedit"
> 
> Step 2: go to your BeeF-Over-Wan directory
> 
> Step 3: do "gedit BeeFOverWan.py"
> 
> Step 4: remove the line 8 and paste " #from termcolor import colored " in line 8
> 
> Now do "python BeeFOverWan.py" and it should work perfectly

You sir are just like your profile picture. A true chad
