### ISSUE TITLE
ImportError: No module named termcolor

### ISSUE THREAD

**Issue by Lilpablo999** [stormshadow07/BeeF-Over-Wan#64]
please can anyone help, isn't working with python2 & 3 here is the error i got
$ python2 BeeFOverWan.py                                                        1 ⨯
Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor
                                        

and i tried to install with pip2 install termcolor but still samething 

please help

**Comment by kaj101** [comment]
i am experiencing the same issue have you figured this out?

**Comment by Lilpablo999** [comment]
> i am experiencing the same issue have you figured this out?

yes bro you just have to install termcolor on your desktop or where you install Beef-over-wan

**Comment by kaj101** [comment]
hello i am still struggling to get this working i get to the point of putting in "python2 BeeFOverWan.py" then i get this error; Traceback (most recent call last):
  File "BeeFOverWan.py", line 8, in <module>
    from termcolor import colored
ImportError: No module named termcolor
i have tried installing termcolor multiple times yet to no avail help would be appreciated.

**Comment by Lilpablo999** [comment]
you need to get python2 pip else download and extract termcolor on your desktop

**Comment by kaj101** [comment]
will do thanks for the help
