### ISSUE TITLE
why does this happen with the regular ngrok links??? 

### ISSUE THREAD

**Issue by discordbot234556789** [stormshadow07/BeeF-Over-Wan#80]
I worked on figuring out solutions for so many hours to the point where i feel my brain breaking apart. I fixed all the errors from the ngrok config spacing and then I run the program and it works and then go to paste my link, paste it and this happens when i press enter:
 
Traceback (most recent call last):
  File "BeeFOverWan.py", line 122, in <module>
    send_to=input(color((' [?] Enter Adress of Link [You are Sending to Victim]: ')))
  File "<string>", line 1
    https://8e61-13-59-43-20.ngrok.io

**Comment by discordbot234556789** [comment]
please help I really do think that this program is dope and i wand to try it.
